# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyreview < Formula
  desc "Terminal UI for code review across multiple Git providers"
  homepage "https://github.com/tauantcamargo/lazyreview"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tauantcamargo/lazyreview/releases/download/v0.10.0/lazyreview_0.10.0_darwin_amd64.tar.gz"
      sha256 "32d3fad7934bf6ee6205f4ea3ae3fe7a482f7119bbbfb75ba05f135229d71f35"

      def install
        bin.install "lazyreview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tauantcamargo/lazyreview/releases/download/v0.10.0/lazyreview_0.10.0_darwin_arm64.tar.gz"
      sha256 "2c444814311c7d30d992ca16cd108be96f9f9db202a42dbfe65d51a86bfcc8c0"

      def install
        bin.install "lazyreview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tauantcamargo/lazyreview/releases/download/v0.10.0/lazyreview_0.10.0_linux_amd64.tar.gz"
      sha256 "edb92f1129588c9756d90a3c693ba8d2a4e802de625d87be1e8dc1e0cbd617f6"
      def install
        bin.install "lazyreview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tauantcamargo/lazyreview/releases/download/v0.10.0/lazyreview_0.10.0_linux_arm64.tar.gz"
      sha256 "ce0af56fb40926ce8f125d368544ced083da92c3678ca34bec450862e4ca9e3e"
      def install
        bin.install "lazyreview"
      end
    end
  end

  test do
    system "#{bin}/lazyreview", "--version"
  end
end
