# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyreview < Formula
  desc "Terminal UI for code review across multiple Git providers"
  homepage "https://github.com/tauantcamargo/lazyreview"
  version "0.44.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tauantcamargo/lazyreview/releases/download/v0.44.0/lazyreview_0.44.0_darwin_amd64.tar.gz"
      sha256 "5bbc1d128bb9ef4f618629d612971415f8390d0c751c9fc77356728d4c969660"

      def install
        bin.install "lazyreview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tauantcamargo/lazyreview/releases/download/v0.44.0/lazyreview_0.44.0_darwin_arm64.tar.gz"
      sha256 "e343011346c128f984078b818b5e0ba86cd6950c15b92f736934ff8dc6e1f83f"

      def install
        bin.install "lazyreview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tauantcamargo/lazyreview/releases/download/v0.44.0/lazyreview_0.44.0_linux_amd64.tar.gz"
      sha256 "87465ce9f54f2287b63fcfe71d36ca03f6435572a02ab0e8d7e993dda77bf21b"
      def install
        bin.install "lazyreview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tauantcamargo/lazyreview/releases/download/v0.44.0/lazyreview_0.44.0_linux_arm64.tar.gz"
      sha256 "e82bd0c16b5929f2a52f63de86e8543b04d2d605f8703ded1a5026921f1c3310"
      def install
        bin.install "lazyreview"
      end
    end
  end

  test do
    system "#{bin}/lazyreview", "--version"
  end
end
