# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Workpulse < Formula
  desc "A minimal, beautiful terminal-based Pomodoro timer"
  homepage "https://github.com/tauantcamargo/workpulse"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tauantcamargo/workpulse/releases/download/v0.1.0/workpulse_0.1.0_darwin_amd64.tar.gz"
      sha256 "bc060acbdf01bedcad0ff70c92e464982f2e705103c33edf22c8b7437d195001"

      def install
        bin.install "workpulse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tauantcamargo/workpulse/releases/download/v0.1.0/workpulse_0.1.0_darwin_arm64.tar.gz"
      sha256 "f6c7a9e874a876b3c12bae4b2fa3947d0aaacbfba67a82352a368d8b2a330a8d"

      def install
        bin.install "workpulse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tauantcamargo/workpulse/releases/download/v0.1.0/workpulse_0.1.0_linux_amd64.tar.gz"
      sha256 "f71037ff23d7d6d05f6fc8331a7828615c32c6a64d89d45cf027ec0c5c5422f1"
      def install
        bin.install "workpulse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tauantcamargo/workpulse/releases/download/v0.1.0/workpulse_0.1.0_linux_arm64.tar.gz"
      sha256 "6bd9eafec6e196355e2c0b54cbcd19ddccb922aca38b6ffdfcbc39004387f0b3"
      def install
        bin.install "workpulse"
      end
    end
  end

  test do
    system "#{bin}/workpulse", "--help"
  end
end
