# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Workpulse < Formula
  desc "A minimal, beautiful terminal-based Pomodoro timer"
  homepage "https://github.com/tauantcamargo/workpulse"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tauantcamargo/workpulse/releases/download/v0.2.0/workpulse_0.2.0_darwin_amd64.tar.gz"
      sha256 "f56926441efdafb9e2635df94cbb97fd42368d2cf238b39de8eadd96a49b12f2"

      def install
        bin.install "workpulse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tauantcamargo/workpulse/releases/download/v0.2.0/workpulse_0.2.0_darwin_arm64.tar.gz"
      sha256 "3285dea7d4b0a9989499d7fc22dc7ed2a66d487a112d6c9d40051d80e6e99b61"

      def install
        bin.install "workpulse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tauantcamargo/workpulse/releases/download/v0.2.0/workpulse_0.2.0_linux_amd64.tar.gz"
      sha256 "e1c6f6384e6245acfe896edf7859cbd728252fc427383f92a63494702c299cff"
      def install
        bin.install "workpulse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tauantcamargo/workpulse/releases/download/v0.2.0/workpulse_0.2.0_linux_arm64.tar.gz"
      sha256 "406ce1e84955e3246e53e401119116020d01c1d0cf3b36aee9a26eb30d8ff571"
      def install
        bin.install "workpulse"
      end
    end
  end

  test do
    system "#{bin}/workpulse", "--help"
  end
end
